MeusJogos/Models/AmigoViewModel.cs
using MeusJogos.Util;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;

namespace MeusJogos.Models
{
    public class AmigoViewModel
    {
        public int IdAmigo { get; set; }
        private string telefone;

        [Display(Name = "Nome do amigo")]
        [Required(ErrorMessage = "Campo obrigatório")]
        [MaxLength(50, ErrorMessage = "Número de caracteres inválido.")]
        public string Nome { get; set; }

        [Display(Name = "Telefone")]
        [Required(ErrorMessage = "Campo obrigatório")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        [RegularExpression("^\\([1-9]{2}\\) [2-9][0-9]{3,4}\\-[0-9]{4}$", ErrorMessage = "Telefone em formato inválido.")]
        public string Telefone //{ get; set; }
         {
            get { return RecursosUtil.AdicionarMascaraTelefone(telefone); }

            set { telefone = value; }
        }
        
        public ICollection<JogoAmigoViewModel> ListaJogosEmprestados { get; set; }
    }
}

MeusJogos/Controllers/AmigoController.cs
using AutoMapper;
using MeusJogos.Business.Interface;
using MeusJogos.Domain.Entities;
using MeusJogos.Models;
using MeusJogos.Util;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace MeusJogos.Controllers
{
    [Authorize]
    [ValidateInput(false)]
    public class AmigoController : Controller
    {
        #region Propriedades (Autowired)

        public IAmigoBusiness AmigoBusiness { get; set; }
        public IUsuarioBusiness UsuarioBusiness { get; set; }
        public IMapper Mapper { get; set; }

        #endregion

        #region Ajax

        [HttpGet]
        public PartialViewResult ListarJogosAmigo(int id)
        {
            var amigo = AmigoBusiness.BuscarAmigo(id);
            var amigoVm = Mapper.Map<Amigo, AmigoViewModel>(amigo);
            return PartialView("~/Views/Amigo/modal/_modalDetalharJogoAmigo.cshtml", amigoVm);
        }

        #endregion

        // GET: Amigo
        public ActionResult Index()
        {
            var lista = AmigoBusiness.ListarAmigos(User.Identity.Name);
            var listaAmigoViewModel = Mapper.Map<List<Amigo>, List<AmigoViewModel>>(lista);

            return View(listaAmigoViewModel);
        }

        // GET: Amigo/Details/5
        public ActionResult Details(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var amigo = AmigoBusiness.BuscarAmigo(id);
            if (amigo == null)
            {
                return HttpNotFound();
            }

            var amigoViewModel = Mapper.Map<Amigo, AmigoViewModel>(amigo);
            return View(amigoViewModel);
        }

        // GET: Amigo/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Amigo/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdAmigo,Nome,Telefone")] AmigoViewModel amigoViewModel)
        {
            if (ModelState.IsValid)
            {
                var usuario = UsuarioBusiness.BuscarUsuarioPorNome(User.Identity.Name);
                var amigo = Mapper.Map<Amigo>(amigoViewModel);
                amigo.IdUsuario = usuario.IdUsuario;
                amigo.Telefone = RecursosUtil.RemoverFormatacao(amigo.Telefone);
                AmigoBusiness.Salvar(amigo);
                return RedirectToAction("Index");
            }
            return View(amigoViewModel);
        }

        // GET: Amigo/Edit/5
        public ActionResult Edit(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var amigo = AmigoBusiness.BuscarAmigo(id);
            if (amigo == null)
            {
                return HttpNotFound();
            }

            var amigoViewModel = Mapper.Map<Amigo, AmigoViewModel>(amigo);
            return View(amigoViewModel);
        }

        // POST: Amigo/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdAmigo,Nome,Telefone")] AmigoViewModel amigoViewModel)
        {
            if (ModelState.IsValid)
            {
                var amigo = Mapper.Map<Amigo>(amigoViewModel);
                var usuario = UsuarioBusiness.BuscarUsuarioPorNome(User.Identity.Name);
                amigo.IdUsuario = usuario.IdUsuario;
                amigo.Telefone = RecursosUtil.RemoverFormatacao(amigo.Telefone);
                AmigoBusiness.Salvar(amigo);
                return RedirectToAction("Index");
            }
            return View(amigoViewModel);
        }
        
        // GET: Amigo/Delete/5
        public ActionResult Delete(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var amigo = AmigoBusiness.BuscarAmigo(id);
            if (amigo == null)
            {
                return HttpNotFound();
            }

            var amigoViewModel = Mapper.Map<Amigo, AmigoViewModel>(amigo);
            return View(amigoViewModel);
        }

        // POST: Amigo/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            AmigoBusiness.Excluir(id);
            return RedirectToAction("Index");
        }
        
    }
}

MeusJogos/Views/Amigo/Create.cshtml
@model MeusJogos.Models.AmigoViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Criar amigo</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control", @placeholder = "Nome", @maxlength = 100 } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telefone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefone, new { htmlAttributes = new { @class = "form-control telefone", @placeholder = "Telefone ou celular", @maxlength = 100 } })
                @Html.ValidationMessageFor(model => model.Telefone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/Scripts/geral.js")
    @Scripts.Render("~/Scripts/jquery.mask.js")
}

MeusJogos/Views/Amigo/Delete.cshtml
@model MeusJogos.Models.AmigoViewModel

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Excluir amigo</h2>

<h3>Tem certeza que deseja excluir o amigo @Model.Nome?</h3>
<div>
    <hr />
    @if (Model.ListaJogosEmprestados.Any())
    {
        <div class="alert alert-danger">
            <b>Atenção!</b> O amigo @Model.Nome possui <a id="detalharJogoAmigo" class="alert-link" href="#">jogos não devolvidos.</a>
        </div>
    }
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telefone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefone)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Excluir" class="btn btn-danger" />
        </div>
    }
    <hr />
    <div>
        @Html.ActionLink("Voltar", "Index")
    </div>

</div>
<div id="containerModal"></div>
@section scripts{
    <script type="text/javascript">
        var app = app || {};
        app.Urls = app.Urls || {};
        app.Urls.urlBase = '@Url.Content("~")';
        app.Urls.urlListarJogosAmigo = '@Url.Action("ListarJogosAmigo", "Amigo")';

        var modelAmigo = {
            IdAmigo: '@Model.IdAmigo'
        };

    </script>
    <script type="text/javascript" src="@Scripts.Url("~/Scripts/geral.js")"></script>
    <script type="text/javascript" src="@Scripts.Url("~/Scripts/Amigo/amigo.js")"></script>
}

MeusJogos/Views/Amigo/Details.cshtml
@model MeusJogos.Models.AmigoViewModel

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Detalhes do amigo</h2>

<div>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telefone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefone)
        </dd>

    </dl>
</div>
<div class="clearfix"></div>
<h4>Jogos emprestados:</h4>
<div class="col-md-12">
    @if (Model.ListaJogosEmprestados.Any())
    {
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th scope="col">Título</th>
                    <th scope="col">Versão</th>
                    <th scope="col">Data da retirada</th>
                    <th scope="col">Data da devolução</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var jogosEmprestados in Model.ListaJogosEmprestados)
                {
                    <tr>
                        <td>@jogosEmprestados.Jogo.Titulo</td>
                        <td>@jogosEmprestados.Jogo.Versao</td>
                        <td>@jogosEmprestados.DataRetirada.ToShortDateString()</td>
                        @if (jogosEmprestados.DataDevolucao.HasValue)
                    {
                            <td>@jogosEmprestados.DataDevolucao.Value</td>
                        }
                        else
                        {
                            <td>A devolver</td>
                        }
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <h5>Nenhum jogo emprestado.</h5>
    }
</div>
<div class="clearfix">
</div>
<p>
    @Html.ActionLink("Alterar", "Edit", new { id = Model.IdAmigo }) |
    @Html.ActionLink("Voltar", "Index")
</p>

MeusJogos/Views/Amigo/Edit.cshtml
@model MeusJogos.Models.AmigoViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Alterar amigo</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telefone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefone, new { htmlAttributes = new { @class = "form-control telefone" } })
                @Html.ValidationMessageFor(model => model.Telefone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/Scripts/geral.js")
    @Scripts.Render("~/Scripts/jquery.mask.js")
}

MeusJogos/Views/Amigo/Index.cshtml
@model IEnumerable<MeusJogos.Models.AmigoViewModel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Amigos cadastrados</h2>
<p>
    @Html.ActionLink("Novo", "Create")
</p>
<table class="table table-striped table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Telefone)
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Telefone)
            </td>
            <td>
                @Html.ActionLink("Detalhar", "Details", new { id = item.IdAmigo }) |
                @Html.ActionLink("Alterar", "Edit", new { id = item.IdAmigo }) |
                @Html.ActionLink("Excluir", "Delete", new { id = item.IdAmigo })
            </td>
        </tr>
    }
</table>