MeusJogos/Models/JogoViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MeusJogos.Models
{
    public class JogoViewModel
    {
        public int IdJogo { get; set; }

        [Display(Name = "Título do jogo")]
        [Required(ErrorMessage = "Campo obrigatório")]
        [MaxLength(80, ErrorMessage = "Número de caracteres inválido.")]
        public string Titulo { get; set; }

        [Display(Name = "Versão do jogo")]
        [MaxLength(20, ErrorMessage = "Número de caracteres inválido.")]
        public string Versao { get; set; }

        [Display(Name = "Data que adquiriu o jogo")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        [DataType(DataType.Date, ErrorMessage = "Data inválida.")]
        public DateTime DataAquisicao { get; set; }

        public ICollection<JogoAmigoViewModel> ListaJogosEmprestados { get; set; }

        public List<JogoViewModel> ListaJogosDisponiveis { get; set; }
    }
}

MeusJogos/Controllers/JogoController.cs
using AutoMapper;
using MeusJogos.Business.Interface;
using MeusJogos.Domain.Entities;
using MeusJogos.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace MeusJogos.Controllers
{
    [Authorize]
    [ValidateInput(false)]
    public class JogoController : Controller
    {
        #region Propriedades (Autowired)

        public IMapper Mapper { get; set; }
        public IJogoBusiness JogoBusiness { get; set; }
        public IUsuarioBusiness UsuarioBusiness { get; set; }

        #endregion

        // GET: Jogos
        public ActionResult Index()
        {
            var listaJogos = JogoBusiness.ListarJogos(User.Identity.Name);
            var listaJogosViewModel = Mapper.Map<List<JogoViewModel>>(listaJogos);
            return View(listaJogosViewModel);
        }

        // GET: Jogos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var jogo = JogoBusiness.BuscarPorId(id.Value);

            if (jogo == null)
            {
                return HttpNotFound();
            }
            var jogoVm = Mapper.Map<JogoViewModel>(jogo);
            return View(jogoVm);
        }

        // GET: Jogos/Create
        public ActionResult Create()
        {
            return View();
        }

        // GET: Jogos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var jogo = JogoBusiness.BuscarPorId(id.Value);
            if (jogo == null)
            {
                return HttpNotFound();
            }
            var jogoViewModel = Mapper.Map<JogoViewModel>(jogo);
            return View(jogoViewModel);
        }

        // GET: Jogos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var jogo = JogoBusiness.BuscarPorId(id.Value);
            if (jogo == null)
            {
                return HttpNotFound();
            }
            var jogoViewModel = Mapper.Map<JogoViewModel>(jogo);
            return View(jogoViewModel);
        }

        // POST: Jogos/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdJogo,Titulo,Versao,DataAquisicao")] JogoViewModel jogoViewModel)
        {
            if (ModelState.IsValid)
            {
                var jogo = Mapper.Map<Jogo>(jogoViewModel);
                var usuario = UsuarioBusiness.BuscarUsuarioPorNome(User.Identity.Name);
                jogo.IdUsuario = usuario.IdUsuario;
                JogoBusiness.Salvar(jogo);

                return RedirectToAction("Index");
            }
            return View(jogoViewModel);
        }

        // POST: Jogos/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdJogo,Titulo,Versao,DataAquisicao")] JogoViewModel jogoViewModel)
        {
            if (ModelState.IsValid)
            {
                var jogo = Mapper.Map<Jogo>(jogoViewModel);
                var usuario = UsuarioBusiness.BuscarUsuarioPorNome(User.Identity.Name);
                jogo.IdUsuario = usuario.IdUsuario;
                JogoBusiness.Salvar(jogo);
                return RedirectToAction("Index");
            }
            return View(jogoViewModel);
        }

        // POST: Jogos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            JogoBusiness.Excluir(id);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public PartialViewResult DetalharJogoAmigo(int id)
        {
            var jogo = JogoBusiness.BuscarPorId(id);
            var jogoEmprestado = jogo.ListaJogosEmprestados.FirstOrDefault();
            var jogoEmprestadoViewModel = Mapper.Map<JogoAmigo, JogoAmigoViewModel>(jogoEmprestado);
            return PartialView("~/Views/Jogo/modal/_modalDetalharJogoAmigo.cshtml", jogoEmprestadoViewModel);
        }
    }
}

MeusJogos/Views/Jogo/Create.cshtml
@model MeusJogos.Models.JogoViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Criar jogo</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        
        <div class="form-group">
            @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Versao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Versao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Versao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataAquisicao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataAquisicao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataAquisicao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Criar" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MeusJogos/Views/Jogo/Delete.cshtml
@model MeusJogos.Models.JogoViewModel

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Excluir jogo</h2>

<h3>Tem certeza que deseja excluir o jogo @Model.Titulo?</h3>
<div>
    <hr />
    @if (Model.ListaJogosEmprestados.Any())
    {
        <div class="alert alert-danger">
            <b>Atenção!</b> O jogo está emprestado para <a id="detalharJogoAmigo" class="alert-link" href="#">algum amigo.</a>
        </div>
    }
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Titulo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Versao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Versao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataAquisicao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataAquisicao)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Excluir" class="btn btn-danger" />
        </div>
    }
    <hr />
    <div>
        @Html.ActionLink("Voltar", "Index")
    </div>
</div>
<div id="containerModal"></div>
@section scripts{
    <script type="text/javascript">
        var app = app || {};
        app.Urls = app.Urls || {};
        app.Urls.urlBase = '@Url.Content("~")';
        app.Urls.urlDetalharJogoAmigo = '@Url.Action("DetalharJogoAmigo", "Jogo")';

        var modelJogo = {
            IdJogo: '@Model.IdJogo'
        };

    </script>
<script type="text/javascript" src="@Scripts.Url("~/Scripts/geral.js")"></script>
    <script type="text/javascript" src="@Scripts.Url("~/Scripts/Jogo/jogo.js")"></script>
}

MeusJogos/Views/Jogo/Details.cshtml
@model MeusJogos.Models.JogoViewModel

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Detalhes do jogo</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Titulo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Versao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Versao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataAquisicao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataAquisicao)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Alterar", "Edit", new { id = Model.IdJogo }) |
    @Html.ActionLink("Voltar", "Index")
</p>

MeusJogos/Views/Jogo/Edit.cshtml
@model MeusJogos.Models.JogoViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Alterar jogo</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        
        <div class="form-group">
            @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Versao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Versao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Versao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataAquisicao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataAquisicao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataAquisicao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MeusJogos/Views/Jogo/Index.cshtml
@model IEnumerable<MeusJogos.Models.JogoViewModel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Jogos cadastrados</h2>
<p>
    @Html.ActionLink("Novo", "Create")
</p>
<table class="table table-striped table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Titulo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Versao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DataAquisicao)
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Titulo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Versao)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DataAquisicao)
            </td>
            <td>
                @Html.ActionLink("Detalhar", "Details", new { id = item.IdJogo }) |
                @Html.ActionLink("Alterar", "Edit", new { id = item.IdJogo }) |
                @Html.ActionLink("Excluir", "Delete", new { id = item.IdJogo })
            </td>
        </tr>
    }
</table>